# https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip

pipeline: 
  terraform:
    image: jmcann/drone-terraform:latest
    plan: false
    sensitive: true
    root_dir: terraform
    # remove these actions for deployment
    actions:
      - validate
      - plan
    vars:
      project:                ${TF_VAR_project}
      region:                 ${TF_VAR_region}
      zone:                   ${TF_VAR_zone}
      credentials_file_path:  ${TF_VAR_credentials_file_path} 
      machine_type:           n1-standard-1
        