# https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip

pipeline: 
  terraform:
    image: jmcann/drone-terraform:latest
    sensitive: true
    root_dir: terraform
    
    # remove these actions for deployment
    actions:
      - validate
      - plan
        